<?php

namespace GetWith\CoffeeMachine\Tests\Unit\Console;

use PHPUnit\Framework\TestCase;

class MoneyEarnCommandTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAssertTrue(): void
    {
        $this->assertTrue(true);
    }
}
